### ISSUE TITLE
Z-height range

### ISSUE THREAD

**Issue by gilpo1** [fo76utils/fo76utils#2]
Would it be possible to implement a parameter for setting a z-height range to render? I'm starting to use this tool to render out interior cells for Fallout 76 and this would be extremely useful for buildings with multiple floors. I can already use the -view parameter to cut down to the floor, but I can't figure out a way to eliminate stuff from below. I appreciate the work you've put into creating these tools and can't thank you enough for what you've already done.

**Comment by fo76utils** [comment]
It should be possible to add a Z limit option, currently, the maximum is 16777216. The range can be reduced by replacing that value in render.cpp, but I will add it as a command line option soon.

**Comment by gilpo1** [comment]
Fantastic! Ideally the parameter would accept 2 values.... a min z-height and a max z-height. So I could render out a single floor at a time without seeing stuff that's above or below the selected range.

**Comment by fo76utils** [comment]
For now, I have added the option for maximum Z, but changing the minimum is not as easy, since it is assumed in more places in the code that the minimum is zero. So, the range can be adjusted by changing both -zmax and the Z offset in -view. Although it would be easy to implement the same effect as a minimum above zero by subtracting it from both values.
